### PR TITLE
Update regex not to include color tags.

### PR DESCRIPTION
**Pull request by MinekPo1**
I don't have the tools to build c# so I can only hope this works. The regex was tested however.

wordRegex: https://regex101.com/r/C3pLwa/1

spaceRegex: https://regex101.com/r/y5vEk5/1/

Note: while wordRegex highlights spaces in the test, they are not actually matched.

Solution to #1

### CODE REVIEW

**Comment by MinekPo1** [comment]
Sadly this wont work as the \K tag is not supported by the C# regex implementation. I will find a different solution.

**Comment by MinekPo1** [comment]
Ok I hope it should work now.

**Review by MinekPo1 — COMMENTED** [review]
The space added in the beginning of value could be removed, however it would require making the regex more complex and I think its a good traidoff.

**Comment by sodiboo** [comment]
Please do not make changes to the Owoify library. It is not mine, but i had to modify it slightly to make it work with Muck's libraries. I want to keep those changes very minimal. Is this possible to do in the text preprocessor?

**Comment by MinekPo1** [comment]
I have only modified `Program.cs`, which I believe is the preprocessor you mentioned.

**Comment by MinekPo1** [comment]
Oh I'm dumb, it's not.

**Comment by MinekPo1** [comment]
The library seems to be under MIT, however I have a possible implementation.

**Comment by MinekPo1** [comment]
Ok, I don't feel like doing that today and I don't know if I will ever get reminded to return so here is my idea:

Both numbers and pipes (`|`) are not affected, even on the ovo level. 
Get all tags in the text (starts with `<`, no spaces, ends with `>`) and placing them in an array or some other container.
Replace all of them in the text with `||<index in the array>||` and pass it on to Owoify.
Loop over each index in the array and replace `||<i>||` with the tag.

To make collisions with normal chat activity less likely a number can be added inside of the double pipes.

This will make all text in <> be not affected, but I don't think its that much of a problem.

I am closing this PR as you have expressed my method to be not acceptable for what you want this library to be, which I understand.

**Comment by sodiboo** [comment]
> The library seems to be under MIT, however I have a possible implementation.

Yeah. It's not about the license. More just that i don't want to edit the library really, and the only reason i've done so is because i actually had to and it would not compile as-is. I guess improvements to the owoification algorithm are welcome in that directory in this repo, but stripping TMP tags is not part of Owoify itself and i want that to be done in the mod itself.

**Pull request closed without merging**
